### ISSUE TITLE
Not working on new UI of leetcode

### ISSUE THREAD

**Issue by manojyadavblack** [madhur/leetcode-format-chrome-extension#13]

**Comment by prabaljainn** [comment]
@madhur @alushpranav @whoibrar 
Hey, sorry for the tag, but I believe LeetCode doesn't use CodeMirror and instead employs something like Monaco Editor. Would you like me to refactor the code to accommodate the new UI of LeetCode?
**I am eager to contribute.**

**Comment by madhur** [comment]
Yes Prabal. Please go ahead. I had tried it but was unable to come up with
solution with Monaco editor. It would be great if you can do it.

**Comment by prabaljainn** [comment]
Yes, Senpai. I am into it. 🙇🏻‍♂️

**Comment by prabaljainn** [comment]
I believe I have, senpai.

![2023-05-18 07-20-49](https://github.com/madhur/leetcode-format-chrome-extension/assets/62801988/c5fddf14-3c9a-4912-a691-4e7e5111a97e)

**Comment by madhur** [comment]
That great @prabaljainn . Yes,  lets have it.

**Comment by prabaljainn** [comment]
Sent you a message on LinkedIn.

**Comment by madhur** [comment]
I have published the latest version of extension, which supports the new UI. Thanks @prabaljainn

**Comment by prabaljainn** [comment]
@madhur Senpai, please close this issue and #11. Thanks to you, I learned about working of Chrome extensions. See you in BLR. 🙇🏻‍♂️.

**Comment by prabaljainn** [comment]
> I believe it's working, senpai. @madhur let's have a meet.
> 
> ![format-demo](https://user-images.githubusercontent.com/62801988/239732359-d476f1d1-aafe-4695-b4eb-c124c2087c31.gif)

add this screenshot if you can.

**Comment by madhur** [comment]
Sure. I'll add it today.

**Comment by madhur** [comment]
> > I believe it's working, senpai. @madhur let's have a meet.
> > ![format-demo](https://user-images.githubusercontent.com/62801988/239732359-d476f1d1-aafe-4695-b4eb-c124c2087c31.gif)
> >       
> >         [
> >           
> >         ](https://user-images.githubusercontent.com/62801988/239732359-d476f1d1-aafe-4695-b4eb-c124c2087c31.gif)
> >         
> >             ![format-demo](https://user-images.githubusercontent.com/62801988/239732359-d476f1d1-aafe-4695-b4eb-c124c2087c31.gif)
> >           
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/62801988/239732359-d476f1d1-aafe-4695-b4eb-c124c2087c31.gif)
> 
> add this screenshot if you can.

Done
