### ISSUE TITLE
Extension is not working on Leetcode from today morning

### ISSUE THREAD

**Issue by abhirajsinha** [madhur/leetcode-format-chrome-extension#16]
Hi, @madhur extension isn't showing up in Leetcode

**Comment by madhur** [comment]
Hi @abhirajsinha , the UI has changed a bit.  Have a look at this image,
https://github.com/madhur/leetcode-format-chrome-extension/blob/master/images/format-demo.gif

Does it appear as per the image?

**Comment by abhirajsinha** [comment]
Yes it is working fine in the updated UI but, I'm still using the Old Ui and in that UI the formatter is not showing up.

**Comment by madhur** [comment]
Ooh. Is the UI switchable? I thought everyone moved to the new UI. How do you go back to the old UI ?

**Comment by abhirajsinha** [comment]
Yes, we can switch the UI from the profile settings.

**Steps:**
1. Open any Problem
2. Click on your profile icon
3. Scroll down to the bottom, there you will see an option of **Revert to old version**

<img width="838" alt="image" src="https://github.com/madhur/leetcode-format-chrome-extension/assets/56290450/c13c8a9a-d15a-4739-892e-174a1bea1b8c">

**Comment by madhur** [comment]
Aah ok. I was not unaware of that. unfortunately, support for old version has been removed in the extension. Let me see if I can add it back.

**Comment by abhirajsinha** [comment]
Sure

**Comment by madhur** [comment]
Hi @abhirajsinha , I have released the new version which works with both old and new UI. Please check it out.

**Comment by abhirajsinha** [comment]
Hi @madhur, yes it is working in both the version, Thank you so much for the support ❤️

**Comment by madhur** [comment]
> Hi @madhur, yes it is working in both the version, Thank you so much for the support heart

Glad that you are liking the extension
