### ISSUE TITLE
Cant Find the Format Button in the NEW UI

### ISSUE THREAD

**Issue by NazimFilzer** [madhur/leetcode-format-chrome-extension#20]

**Comment by SunnyScenery** [comment]
Same, cannot find the format button in both old and new UI. shortcut is also not working.

**Comment by madhur** [comment]
@SunnyScenery  @NazimFilzer  Could you provide a screenshot? Looks something has changed for few users.

**Comment by SunnyScenery** [comment]
<img width="1749" alt="image" src="https://github.com/madhur/leetcode-format-chrome-extension/assets/46459544/dbf7df4c-2626-4933-8c7c-2f484c2969d1">

An example would be this. There should be the format button there. Below there is a part saying `System error: net::ERR_BLOCKED_BY_CLIENT`. This might be related to this extension.

**Comment by madhur** [comment]
@SunnyScenery  This is the old UI right, not the new one.

In the old UI, you should be able to see the button at right corner as shown in screenshot below.
![image](https://github.com/madhur/leetcode-format-chrome-extension/assets/509431/9eb4bc32-1c0c-4e47-8578-5b4cb40546ef)

I do agree that there is a bug with new UI which I am looking into.

Just wanted to make sure it doesn't exist with old UI as well.

**Comment by madhur** [comment]
@NazimFilzer  I have released the new version with the fix. Please check it out.
