### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'getValue')

### ISSUE THREAD

**Issue by hbarsaiyan** [madhur/leetcode-format-chrome-extension#22]
Getting the following error when clicking Format button:

```
TypeError: Cannot read properties of undefined (reading 'getValue')
    at getCodev2 (script.js:303:24)
    at HTMLButtonElement.formatCodeMonacov2 (script.js:254:20)
    at HTMLButtonElement.i (_app-3a1d4caef7aacd27.js:1:1711803)
```

**Comment by madhur** [comment]
Hi @hbarsaiyan , which UI of leetcode you are using? Could you share a screenshot.

**Comment by hbarsaiyan** [comment]
I am using the new Dynamic Layout UI and version 1.7 of leetcode-format from Chrome Webstore.

![image](https://github.com/madhur/leetcode-format-chrome-extension/assets/37732050/3ef7d3bb-e8bb-45a4-bf3a-d51185d5ae2a)

**Comment by madhur** [comment]
Thanks for the PR. Let me check and get back.

**Comment by madhur** [comment]
I have submitted the fixed version to chrome webstore. Should be published in couple of days. Thanks for the bug report.

**Comment by madhur** [comment]
@hbarsaiyan  The fix has been released on chrome console. Pls check it out.

**Comment by hbarsaiyan** [comment]
It is working fine now.
