### ISSUE TITLE
Requesting for Firefox / Bookmarklet

### ISSUE THREAD

**Issue by whoibrar** [madhur/leetcode-format-chrome-extension#5]
It would be great if this app could work on firefox as well. 

If porting the complete code is note possible, then probably turning this into a simple js bookmarklet that can be used cross-platform and cross browsers?

**Comment by madhur** [comment]
Hi @whoibrar 

This is published for firefox as well
https://addons.mozilla.org/en-US/firefox/addon/leetcode-format/

Let me know if you face any issues.

**Comment by whoibrar** [comment]
Oh Great! I didn't know it already existed.

I've added a link to the firefox version in ReadMe and submitted a [pull request.](https://github.com/madhur/leetcode-format-chrome-extension/pull/6). That should help direct the firefox users.
