### ISSUE TITLE
Needed a shortcut key to format the code.

### ISSUE THREAD

**Issue by Nurexcoder** [madhur/leetcode-format-chrome-extension#8]
I think it would be so much helpful if this extension also have a shortcut button to format code. Ex:- CTRL+SHIFT+I.

**Comment by imsoumya18** [comment]
@Nurexcoder Good idea. As in VS Code, we press (Ctrl + Shift + I), it would be helpful in LeetCode too. But, (Ctrl + Shift + I) is already reserved for launching Page Inspect. I shall look into making another key combination.

**Comment by imsoumya18** [comment]
@madhur I have made a PR on this. Please review that.

**Comment by madhur** [comment]
Thanks @imsoumya18 . Sure, will check that out.

**Comment by madhur** [comment]
@imsoumya18  I have merged the PR. Thanks.
New changes will be reflected in chrome store after approval.

**Comment by imsoumya18** [comment]
Thank you very much @madhur . This was my first PR and that got merged.
